### ISSUE TITLE
Build all targets by default

### ISSUE THREAD

**Issue by kvark** [evmar/n2#53]
Running n2 on a project that currently uses ninja, I get:
> n2: error: no path specified and no default

I think `ninja` just builds all targets if it doesn't see a default?

**Comment by evmar** [comment]
You are correct about ninja's behavior here.  This is easy enough to change in the code, but it also was kinda intentional in that I think ninja's behavior is possibly not a good default.

If you wanted to change this yourself, it's around here:
https://github.com/evmar/n2/blob/6b4fb1a249a01891d68fcd9b6ceef1f2b3c788ba/src/run.rs#L71
you'd need to want_fileid for all fileids in the graph.

**Comment by kvark** [comment]
I was under impression that `n2` tries to be compatible with `ninja`, at least under a mode. Is this not a goal?

**Comment by evmar** [comment]
Compatible in the sense of being able to load the files, but the UI and behavior isn't otherwise necessarily the same.
