### ISSUE TITLE
Does it need sh?

### ISSUE THREAD

**Issue by matklad** [evmar/n2#81]
This is mostly a "what if?" discussion, not really an issue, so feel free to close!

One thing that always bugs me about build systems is how they often bottom out at shell, which introduces implicit dependency on the environment: `/bin/sh` might behave differently on different machines, and it doesn't exist on windows. There's also performance angle here --- there's a whole extra process between the compiler and the build system, and, for _mostly_ no-op builds, I imagine it might add some overhead? 

That's why I was a bit surprised to learn that n2 uses sh:

https://github.com/evmar/n2/blob/599e162e7badb7244802cbd434f36038084aec21/src/process_posix.rs#L85

I would have expected something like deno_task_shell:

https://github.com/denoland/deno_task_shell

That is, implementing minimal shell in n2 itself, to make sure that behavior is hermetic, cross platform, and doesn't require an extra process (of course, the users can themselves type `sh -c` in the task definition if they need a shell). 

I am wondering if there are some deep reasons to use the shell here which I might be missing? Is it perhaps "n2 wants to treat command as a string, without any interpretation, that works on windows and needs sh on Unix?"

**Comment by evmar** [comment]
First, as an underlying principle n2 needs to handle Ninja semantics, and Ninja semantics is shell, so that is sort of set in stone.

I think this question you're interested might instead be: why does Ninja rely on shell?

To start with, Ninja works with command lines as strings not arrays, so there's no way for the person generating the `.ninja` file construct an argv array directly as appropriate for spawning.  This is arguably a design mistake in Ninja, but it's pretty deep within Ninja's semantics; we'd need array-manipulation primitives all over to not behave this way and it'd be a pretty big change.  (It might make some things nicer though, see hacks like `$in_newline` in Ninja...) And it's also the case that the native format for command lines on Windows is strings, not arrays, so even if Ninja supported arrays we'd still need some alternative on Windows etc.  (More discussion of Windows command lines: https://neugierig.org/software/blog/2011/10/quoting.html )

Next, and closer to what you're asking, is why we use POSIX `/bin/sh` instead of our own parser like Deno's.  I think the main reason is that `/bin/sh` parsing is what people expect when talking about Unix command lines.  For example it's common for people to write commands like `my-compiler && other-command` and meaning of that `&&` is understood by shell, as are all the rules around quoting and environment variable references and PATH expansion and so on.  Re hermeticity, `/bin/sh` is specified by POSIX and its behavior is nailed down well across platforms.

It's possible to reimplement the shell logic in n2, but the only reasons I can see would be:

1. To save a process invocation.  But in practice on Unixes spawning `/bin/sh` is a thing done all over and is plenty fast, and spawning processes is not really in the n2 critical path.  For a no-op build we don't spawn anything, and if we do end up spawning a process it's probably something heavy like a compiler where `/bin/sh` doesn't add much weight.
2. Cross-platform portability to Windows.  But a build system targeting Windows is almost certainly going to be invoking different programs on Windows, at least for C++, but also for path reasons, at which point you are generating different command lines anyway and cross-platform compatibility isn't too helpful.

PS: Originally Ninja spawned Windows processes via the Windows shell as well, to make `somecommand && echo hello` work, but my recollection is that the process overhead there does start to matter and also there's a random command-line-length limit.

**Comment by matklad** [comment]
Thanks, that fully answers my question and then some, learned a bunch of things!
